services:
  twserver:
    image: k4rian/twserver:latest
    container_name: twserver
    hostname: twserver
    volumes:
      - data:/home
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080/tcp
    restart: unless-stopped

volumes:
  data: